site_name: Kastle
repo_url: https://github.com/Essay97/kastle-engine
repo_name: Essay97/kastle-engine
nav:
  - Home: index.md
  - Start Here:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Your first game: getting-started/first-game.md
  - Players:
      - Players guide: play.md
  - Developers:
      - Quickstart:
          - Project setup: develop/project-setup.md
          - Your first game: develop/first-game.md
          - Expanding the game: develop/expanding.md
      - Advanced topics:
          - Starting and ending the game: develop/start-end.md
          - Rooms and connections: develop/rooms.md
          - Items: develop/items.md
          - Characters and Dialogues: develop/characters.md
          - Metadata: develop/metadata.md
          - Using multiple files: develop/multiple-files.md
          - Game patterns: develop/patterns.md
          - Distributing your game: develop/distributing.md
      - API Reference: "http://localhost/dokka" # TODO change it with the production link
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: amber
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
